### ISSUE TITLE
[DevOps] Create project workspace for Xamarin test bench

### ISSUE THREAD

**Issue by DamianSuess** [xenoinc/CodeDevOps#10]
As a user, I would like for Xeno.DevOps to be able to create a basic workspace for my Xamarin test bench projects. This would include the bare minimum project files needed - unlike a sanctioned project which required full documentation and different folder structure.

## Tasks
* [ ] Ask for project title and type
* [ ] Create sample files
* [ ] Create subfolder with files
* [ ] Initialize and auto-add files

## Acceptance Criteria
The following files and folder structure should be created
* readme.md
* .gitignore
* .editorconfig
* CodeMaid (optional)
* license (optional)

## Out of Scope
* Create template project

**Comment by DamianSuess** [comment]
Not needed. Use template projects instead
